config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  delete '/curiosities/:id', to: 'curiosities#destroy', as: 'curiosity'
  get '/curiosities/:id', to: 'curiosities#show', as: 'curiosity2'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/curiosity.rb
class Curiosity < ApplicationRecord
    validates :category, inclusion: { in: ["Penderie", "Coffre a jouets", "Vaiselle", "Decorations", "Amis", "Bibliotheque"],
    message: "%{value} is not a valid category" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/curiosities_controller.rb
class CuriositiesController< ApplicationController

  def show
    @curiosity = Curiosity.find(params[:id])
  end

  def destroy
    @curiosity = Curiosity.find(params[:id])
    @curiosity.delete

    redirect_to root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @my_curiosities = Curiosity.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/curiosities/show.html.erb
<h1> Benefits <%= @curiosity.description %></h1>

<ul>
  <li> Improves flexibility </li>
  <li> Helps strenghten the musscles </li>
</ul>

<h2> Even more information about <%= @curiosity.name %></h2>

app/views/home/index.html.erb
<% @my_curiosities.each do |curiosity| %>
<h1><%= curiosity.name %></h1>
<p><%= curiosity.description %></p>
<img title="<%= curiosity.image_text %>" src="<%= curiosity.image_url %>"></img>
<p><%= link_to 'More information', curiosity_path(curiosity) %></p>

<p><%= link_to('<button  type="button" class="btn btn-default btn-lg"> delete <span class"glyphicon glyphicon-star" aria-hidden="true"></span></button>'.html_safe, curiosity_path(curiosity), method: :delete, data: {confirm: 'Message de confirmation'}) %></p>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Curiosite" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Curiosite</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", "/path1"  %></li>
            <li><%= link_to "Classes", "/path2"  %></li>
            <li><%= link_to "Schedule", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Want to know more?</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Find out about our:</li>
              <li><%= link_to "Teachers", "/path1"  %></li>
              <li><%= link_to "Locations", "/path2"  %></li>
              <li><%= link_to "Food", "/path3"  %></li>
            </ul>

        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Dropdown
          <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </div>

          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Where Is My Mat 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>